#!/bin/sh

# Find out what to diff against. Usually it's HEAD
if git rev-parse --verify HEAD >/dev/null 2>&1
then
  against=HEAD
else
  # Initial commit: diff against an empty tree object
  against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# If there are whitespace errors, print the offending file names and fail.
if test "$(git diff-index --check --cached $against --)"
then
  echo "COMMIT ABORTED! Trailing whitespaces detected in following files:"
  exec git diff-index --check --cached $against --
fi

# Fail if debug statements are present in the diff
BLACKLIST="debugger\|binding.pry\|binding.remote_pry\|save_and_open_page\|console\.log("
for FILE in `git diff-index --name-status --cached $against -- | grep ".rb" | cut -c3-`
do
  # Check if the file contains one of the words from BLACKLIST
  if grep -w $BLACKLIST $FILE > /dev/null
  then
    echo "COMMIT ABORTED! $FILE contains a stray debug statement. Please remove it."
    echo "Following statements are forbidden: $BLACKLIST"
    exit 1
  fi
done